### ISSUE TITLE
Tracking Issue to rule them all

### ISSUE THREAD

**Issue by Feliix42** [fsr/kif470-heft#3]
## Content des Heftes (sortiert):

- [x] Cover (@EddyLoose)
- [x] Zeitplan (erste Seite) (@cirdeirf)
- [x] Inhaltsverzeichnis (@feliix42)
- [x] Grußwort/Vorwort (@manuelthieme)
  - evtl. Hashtags/Kommunikationskanäle
- [x] Organisatorisches (@feliix42)
  - Kontaktdaten Orga, ÖPNV, Internet, Strom, ...
- [x] Where & When (@Kleinkop)
  - Essen, Aufenthaltsgebäude, Orte, Duschen, ...
- [x] Hackerbrausenvorträge **(who?)**
- [x] about:dresden (@ChrissisCorner)
  - Terminkollissionen, mehr Essensoptionen, Themenstadtplan, ...
- [x] Sponsoren **(who?)**
- [x] Appendix & Redaktionsinformationen + Mail-Kontakt (vorletzte Seite) (@cirdeirf + @feliix42)
- [x] Campusplan (Haltestellen markieren) (@EddyLoose)
- [x] Fakultätsplan (außen hinten) (@EddyLoose)

### Variable Position im Heft
- [ ] Engelwerbung
- [x] Werbung

## Post Processing
- [ ] Proof-Read
- [x] Layout

**Comment by Feliix42** [comment]
- [x] Turnhallen: Duschen bei Organisatorisches
- [x] Linkliste übernehmen und QR-Codes erstmal drinnen lassen. Können ja später wieder raus ¯\\\_(ツ)_/¯ 
- [x] verschieben "Agenda 2019" nach "Where & When" und umbenennen zu "Hackerbrausen"
- [x] Amend Appendix: _"Das Wichtigste auf einen Blick"_ als Box oberhalb der Redaktionsinfos
## Where & When
- [x] Don't Eat & drink > "Where and When"
- [x] PC-Pools: Stillarbeitsplätze, wenn keine AKs da sind, die anderen Räume streichen
- [x] kleiner Text zum Barkhausenbau
- [x] Mensa Firat? ( ͡° ͜ʖ ͡°)
